export const pa_0 = { padding: '0' };

export const sHelpers = {
  textTransform: {
    uppercase: { textTransform: 'uppercase' },
    lowercase: { textTransform: 'lowercase' },
  },
  fontWeight: {
    [200]: { fontWeight: '200' },
    [400]: { fontWeight: '400' },
    [600]: { fontWeight: '600' },
    [800]: { fontWeight: '800' },
  },

  textAlign: {
    left: { textAlign: 'left' },
    right: { textAlign: 'right' },
    center: { textAlign: 'center' },
  },
  margin: {
    zero: { margin: '0' },
    rem1: { margin: '1rem' },
    rem2: { margin: '2rem' },
    rem3: { margin: '3rem' },
    rem4: { margin: '4rem' },
    rem5: { margin: '5rem' },
  },
  marginTop: {
    zero: { marginTop: '0' },
    rem1: { marginTop: '1rem' },
    rem2: { marginTop: '2rem' },
    rem3: { marginTop: '3rem' },
    rem4: { marginTop: '4rem' },
    rem5: { marginTop: '5rem' },
  },

  marginRight: {
    zero: { marginRight: '0' },
    rem1: { marginRight: '1rem' },
    rem2: { marginRight: '2rem' },
    rem3: { marginRight: '3rem' },
    rem4: { marginRight: '4rem' },
    rem5: { marginRight: '5rem' },
  },
  marginBottom: {
    zero: { marginBottom: '0' },
    rem1: { marginBottom: '1rem' },
    rem2: { marginBottom: '2rem' },
    rem3: { marginBottom: '3rem' },
    rem4: { marginBottom: '4rem' },
    rem5: { marginBottom: '5rem' },
  },
  marginLeft: {
    zero: { marginLeft: '0' },
    rem1: { marginLeft: '1rem' },
    rem2: { marginLeft: '2rem' },
    rem3: { marginLeft: '3rem' },
    rem4: { marginLeft: '4rem' },
    rem5: { marginLeft: '5rem' },
  },
  marginX: {
    zero: { marginLeft: '0', marginRight: '0' },
    rem1: { marginLeft: '1rem', marginRight: '1rem' },
    rem2: { marginLeft: '2rem', marginRight: '2rem' },
    rem3: { marginLeft: '3rem', marginRight: '3rem' },
    rem4: { marginLeft: '4rem', marginRight: '4rem' },
    rem5: { marginLeft: '5rem', marginRight: '5rem' },
    remHalf: { marginLeft: '0.5rem', marginRight: '0.5rem' },
  },
  marginY: {
    zero: { marginTop: '0', marginBottom: '0' },
    rem1: { marginTop: '1rem', marginBottom: '1rem' },
    rem2: { marginTop: '2rem', marginBottom: '2rem' },
    rem3: { marginTop: '3rem', marginBottom: '3rem' },
    rem4: { marginTop: '4rem', marginBottom: '4rem' },
    rem5: { marginTop: '5rem', marginBottom: '5rem' },
  },
  paddingX: {
    zero: { paddingLeft: '0', marginRight: '0' },
    rem1: { paddingLeft: '1rem', paddingRight: '1rem' },
    rem2: { paddingLeft: '2rem', paddingRight: '2rem' },
    rem3: { paddingLeft: '3rem', paddingRight: '3rem' },
    rem4: { paddingLeft: '4rem', paddingRight: '4rem' },
    rem5: { paddingLeft: '5rem', paddingRight: '5rem' },
    remHalf: { paddingLeft: '0.5rem', paddingRight: '0.5rem' },
  },
  paddingY: {
    zero: { paddingTop: '0', marginBottom: '0' },
    rem1: { paddingTop: '1rem', paddingBottom: '1rem' },
    rem2: { paddingTop: '2rem', paddingBottom: '2rem' },
    rem3: { paddingTop: '3rem', paddingBottom: '3rem' },
    rem4: { paddingTop: '4rem', paddingBottom: '4rem' },
    rem5: { paddingTop: '5rem', paddingBottom: '5rem' },
  },

  padding: {
    zero: { padding: '0' },
    rem1: { padding: '1rem' },
    rem2: { padding: '2rem' },
    rem3: { padding: '3rem' },
    rem4: { padding: '4rem' },
    rem5: { padding: '5rem' },
    remHalf: { padding: '0.5rem' },
  },
  paddingTop: {
    zero: { paddingTop: '0' },
    rem1: { paddingTop: '1rem' },
    rem2: { paddingTop: '2rem' },
    rem3: { paddingTop: '3rem' },
    rem4: { paddingTop: '4rem' },
    rem5: { paddingTop: '5rem' },
    remhalf: { paddingTop: '0.5rem' },
  },

  paddingRight: {
    zero: { paddingRight: '0' },
    rem1: { paddingRight: '1rem' },
    rem2: { paddingRight: '2rem' },
    rem3: { paddingRight: '3rem' },
    rem4: { paddingRight: '4rem' },
    rem5: { paddingRight: '5rem' },
    remHalf: { paddingRight: '0.5rem' },
  },
  paddingBottom: {
    zero: { paddingBottom: '0' },
    rem1: { paddingBottom: '1rem' },
    rem2: { paddingBottom: '2rem' },
    rem3: { paddingBottom: '3rem' },
    rem4: { paddingBottom: '4rem' },
    rem5: { paddingBottom: '5rem' },
    remHalf: { paddingBottom: '0.5rem' },
  },
  paddingLeft: {
    zero: { paddingLeft: '0' },
    rem1: { paddingLeft: '1rem' },
    rem2: { paddingLeft: '2rem' },
    rem3: { paddingLeft: '3rem' },
    rem4: { paddingLeft: '4rem' },
    rem5: { paddingLeft: '5rem' },
    remHalf: { paddingLeft: '0.5rem' },
  },
};
